// integrations/react/source/createStore.ts
import type { ApiResponse } from "@digitak/gravity";
import { createStoreData } from "@digitak/gravity/store/createStoreData";
import type { Store } from "./Store.js";
import { useState } from "react";

export const createStore = <Data>(
	fetcher: () => Promise<ApiResponse<Data>>,
): Store<Data> => {
	const storeData = createStoreData<Data>();

	const [store, setStore] = useState({
		...storeData,
		refresh: async () => {
			setStore({ ...store, isRefreshing: true });
			const response = await fetcher();
			setStore({
				...store,
				...response,
				isLoading: false,
				isRefreshing: false,
				lastRefreshAt: Date.now(),
			} as Store<Data>);
		},
	} as Store<Data>);

	return store;
};

// packages/gravity-solid/source/createStore.ts
import { createStoreData } from "@digitak/gravity/store/createStoreData";
import { StoreData } from "@digitak/gravity/store/StoreData";
import { updateStoreData } from "@digitak/gravity/store/updateStoreData";
import { createStore as createSolidStore } from "solid-js/store";
import type { Store } from "./Store.js";
import type { DefineStoreInterface } from "@digitak/gravity/store/defineApiWithStore";

export const createStore: DefineStoreInterface<
	Store<unknown>
>["createStore"] = (fetcher) => {
	const store = createSolidStore<StoreData<unknown>>({
		...createStoreData(),
		refresh: async () => {
			setStoreData({ isRefreshing: true });
			for await (const data of fetcher()) {
				setStoreData(updateStoreData({ ...getStoreData() }, data));
			}
			setStoreData({ isRefreshing: false });
		},
	});
	const getStoreData = () => store[0];
	const setStoreData = (data: Partial<StoreData<unknown>>) => store[1](data);
	return getStoreData();
};

export const create = (init, $store) => {
	const [store, setStore] = createSolidStore($store);
	init(setStore);
	return store;
};
